export { default as ArrowFilledAltFromBottomIcon } from './arrow-filled-alt-from-bottom.svg'
export { default as ArrowFilledAltToBottomIcon } from './arrow-filled-alt-to-bottom.svg'
export { default as Variable } from './var.svg'
export { default as DelCol } from './delete-col.svg'
export { default as DelRow } from './delete-row.svg'
export { default as FilledFileIcon } from './file.svg'
export { default as ExportPDF } from './export-pdf.svg'
export { default as DelTable } from './delete-table.svg'
export { default as Print } from './print.svg'
export { default as FileWordIcon } from './file-word.svg'
export { default as SaveIcon } from './save.svg'
export { default as AlignMiddle } from './align-vertically.svg'
export { default as AlignBottom } from './align-bottom.svg'
export { default as AlignTop } from './align-top.svg'
export { default as NoBorder } from './no-border.svg'

export { default as Hr } from 'jodit/src/styles/icons/hr.svg'
// export { default as Ok } from 'jodit/src/styles/icons/ok.svg'
export { default as Ol } from 'jodit/src/styles/icons/ol.svg'
// export { default as Th } from 'jodit/src/styles/icons/th.svg'
export { default as Ul } from 'jodit/src/styles/icons/ul.svg'
export { default as FileInvoiceIcon } from './file-invoice.svg'
// export { default as Crop } from 'jodit/src/styles/icons/crop.svg'
// export { default as Copy } from 'jodit/src/styles/icons/copy.svg'
// export { default as Dots } from 'jodit/src/styles/icons/dots.svg'
// export { default as File } from 'jodit/src/styles/icons/file.svg'
export { default as Font } from 'jodit/src/styles/icons/font.svg'
export { default as Left } from 'jodit/src/styles/icons/left.svg'
export { default as Link } from 'jodit/src/styles/icons/link.svg'
export { default as LineHeight } from 'jodit/src/styles/icons/line-height.svg'
// export { default as Lock } from 'jodit/src/styles/icons/lock.svg'
// export { default as Menu } from 'jodit/src/styles/icons/menu.svg'
export { default as Plus } from 'jodit/src/styles/icons/plus.svg'
export { default as Redo } from 'jodit/src/styles/icons/redo.svg'
// export { default as Save } from 'jodit/src/styles/icons/save.svg'
export { default as Undo } from 'jodit/src/styles/icons/undo.svg'
// export { default as Bin } from 'jodit/src/styles/icons/bin.svg'
// export { default as Cut } from 'jodit/src/styles/icons/cut.svg'
// export { default as Eye } from 'jodit/src/styles/icons/eye.svg'
export { default as Bold } from 'jodit/src/styles/icons/bold.svg'
export { default as Brush } from 'jodit/src/styles/icons/brush.svg'
// export { default as Check } from 'jodit/src/styles/icons/check.svg'
// export { default as Enter } from 'jodit/src/styles/icons/enter.svg'
export { default as Image } from 'jodit/src/styles/icons/image.svg'
export { default as Merge } from 'jodit/src/styles/icons/merge.svg'
// export { default as Omega } from 'jodit/src/styles/icons/omega.svg'
// export { default as Paste } from 'jodit/src/styles/icons/paste.svg'
// export { default as Print } from 'jodit/src/styles/icons/print.svg'
export { default as Right } from 'jodit/src/styles/icons/right.svg'
export { default as Table } from 'jodit/src/styles/icons/table.svg'
export { default as Cancel } from 'jodit/src/styles/icons/cancel.svg'
export { default as AddRow } from './add-row.svg'
export { default as Center } from 'jodit/src/styles/icons/center.svg'
// export { default as Dedent } from 'jodit/src/styles/icons/dedent.svg'
export { default as Eraser } from 'jodit/src/styles/icons/eraser.svg'
// export { default as Folder } from 'jodit/src/styles/icons/folder.svg'
// export { default as Indent } from 'jodit/src/styles/icons/indent.svg'
export { default as Italic } from 'jodit/src/styles/icons/italic.svg'
// export { default as Pencil } from 'jodit/src/styles/icons/pencil.svg'
// export { default as Resize } from 'jodit/src/styles/icons/resize.svg'
// export { default as Search } from 'jodit/src/styles/icons/search.svg'
// export { default as Shrink } from 'jodit/src/styles/icons/shrink.svg'
export { default as Source } from 'jodit/src/styles/icons/source.svg'
export { default as Splitg } from 'jodit/src/styles/icons/splitg.svg'
// export { default as Splitv } from 'jodit/src/styles/icons/splitv.svg'
// export { default as Unlink } from 'jodit/src/styles/icons/unlink.svg'
// export { default as Unlock } from 'jodit/src/styles/icons/unlock.svg'
// export { default as Update } from 'jodit/src/styles/icons/update.svg'
export { default as Upload } from 'jodit/src/styles/icons/upload.svg'
// export { default as Valign } from 'jodit/src/styles/icons/valign.svg'
// export { default as ThList } from 'jodit/src/styles/icons/th-list.svg'
export { default as Chevron } from 'jodit/src/styles/icons/chevron.svg'
export { default as Justify } from 'jodit/src/styles/icons/justify.svg'
// export { default as Outdent } from 'jodit/src/styles/icons/outdent.svg'
// export { default as Palette } from 'jodit/src/styles/icons/palette.svg'
// export { default as Resizer } from 'jodit/src/styles/icons/resizer.svg'
// export { default as AngleUp } from 'jodit/src/styles/icons/angle-up.svg'
// export { default as ArrowsH } from 'jodit/src/styles/icons/arrows-h.svg'
export { default as Fontsize } from 'jodit/src/styles/icons/fontsize.svg'
export { default as FullSize } from 'jodit/src/styles/icons/fullsize.svg'
export { default as Subscript } from 'jodit/src/styles/icons/subscript.svg'
// export { default as Settings } from 'jodit/src/styles/icons/settings.svg'
export { default as AddColumn } from 'jodit/src/styles/icons/addcolumn.svg'
export { default as Paragraph } from 'jodit/src/styles/icons/paragraph.svg'
export { default as Underline } from 'jodit/src/styles/icons/underline.svg'
// export { default as AngleDown } from 'jodit/src/styles/icons/angle-down.svg'
// export { default as AngleLeft } from 'jodit/src/styles/icons/angle-left.svg'
// export { default as ArrowsAlt } from 'jodit/src/styles/icons/arrows-alt.svg'
// export { default as SelectAll } from 'jodit/src/styles/icons/select-all.svg'
// export { default as Attachment } from 'jodit/src/styles/icons/attachment.svg'
// export { default as CopyFormat } from 'jodit/src/styles/icons/copyformat.svg'
// export { default as AngleRight } from 'jodit/src/styles/icons/angle-right.svg'
// export { default as InfoCircle } from 'jodit/src/styles/icons/info-circle.svg'
export { default as Superscript } from 'jodit/src/styles/icons/superscript.svg'
// export { default as ChainBroken } from 'jodit/src/styles/icons/chain-broken.svg'
// export { default as CheckSquare } from 'jodit/src/styles/icons/check-square.svg'
export { default as Strikethrough } from 'jodit/src/styles/icons/strikethrough.svg'
